name: pvparena
author: slipcor
main: net.slipcor.pvparena.PVPArena
version: 0.6.35.1
website: http://dev.bukkit.org/server-mods/pvp-arena
commands:
    pvparena:
        description: Base commands for the PVP arena.
        aliases: ['pa']
        usage: |
            /pvparena help
permissions:
    pvparena.*:
        description: Gives access to all commands
        children:
            pvparena.admin: true
            pvparena.telepass: true
            pvparena.user: true
    pvparena.admin:
        description: Allows you to administrate arenas
        default: op
    pvparena.create:
        description: Allows you to create and administrate an arena
        default: op
    pvparena.telepass:
        description: Allows you to teleport while in an arena
        default: op
    pvparena.user:
        description: Allows you to use the arena
        default: true